language: generic
sudo: required
services:
  - docker

before_instlall:
  - docker build -t quintinsheridan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true quintinsheridan/docker-react npm run test
